version: 3
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
endpoint: http://localhost:5080
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
